### ISSUE TITLE
macro can't wait end sentence !

### ISSUE THREAD

**Issue by elpimous** [aichaos/rivescript-python#110]
hi, here is what i need to do : 
```
+ bye
- ok. see you soon. <call>returnhome</call>
```

the returnhome macro let the robot return to dock, but i need to hear sentence before moving !
And actually, I don't hear anything, and the macro starts !!
Didn't find solution !

**Comment by kirsle** [comment]
When RiveScript encounters a `<call>` tag, it runs that function and expects a string response that it can substitute into the reply in place of the original `<call>` tag. So if your program is waiting for `reply()` to return before reading the response to you out loud, this won't get to happen until after that `<call>` tag has finished.

I have two ideas for you:

* Program a special case into your bot that you handle *outside* of RiveScript. For example, instead of using a `<call>` tag, make up your own custom tag like `<return_home>` and put that in the reply. The result from `rs.reply()` would contain the literal text `"<return_home>"` and you could look for this and handle it accordingly.

    ```python
    reply = rs.reply(user, message)
    text_to_speech.say(reply)  # read reply out loud however you do that
    if "<return_home>" in reply:  # look for your custom tag
        return_home()  # run this function here after the reply's been read
    ```

* Look into ways to make your object macro asynchronous. Python 3 has [asyncio](https://docs.python.org/3/library/asyncio.html) which has also been backported to Python 2, or [Twisted](https://twistedmatrix.com/trac/) might be another option. The general idea is that your object macro should somehow be able to "fork" and "run a function in the background", but be allowed to `return` a string right away. This way the `<call>` function can return quickly and RiveScript can return a string response, and your forked function runs in the background.

    However, I haven't done any async programming in Python and don't know the exact methods for how to do this. As a JavaScript example, this is equivalent to what I'm thinking:

    ```javascript
    function needsStringResponse(message) {
        // setTimeout "forks" and runs in the background asynchronously
        setTimeout(function() {
            console.log("logged after 5 seconds");
        }, 5000);

        // this `return` will return a string immediately, and then
        // 5 seconds later the function above runs.
        return "a string";
    }
    ```

**Comment by elpimous** [comment]
Hi Noah. What a Big answer !! Thanks a lot.
Well I think I'll choose your first idea, and look for the tag, to launch a function.
(or directly use my tts (text ot speech) command in front of the <returnhome> macro !
Rivescript is very powerfull !!!
Thanks Noah
