### ISSUE TITLE
could i use multiple % in same sequence ?

### ISSUE THREAD

**Issue by elpimous** [aichaos/rivescript-python#64]
ex : 

```
--------------------------
+ i leave
- ok i change question
--------------------------
+ send question
- are you ok
- are you ready
--------------------------
+ yes
% are you ok
- `good`

+ yes
% are you ready
- good

+ no
% are you ok
- bad

+ no
% are you ready
- bad

+ *
% are you ok
% are you ready
- @i leave
```
Is there any possibility to use multiple % like in previous star trigger ?
Thanks all

**Comment by kirsle** [comment]
It's not very well documented, but the `%` command works the same as `+` except it tests the bot's last message.

So you can do this:

```
+ *
% are you (ok|ready)
- {@i leave}
```

If you need to catch the "stars" in the `%` command, use `<botstar>` instead of `<star>` (it works the same as `<star>`, so i.e. `<botstar1>`, `<botstar2>` for multiple wildcards).

**Comment by elpimous** [comment]
really good Kirsle.
Thanks for speed reply.
Your AI is a very powerfull product ! thanks for your work...and service.
Vincent
