### ISSUE TITLE
Issues with parenthesis and variables

### ISSUE THREAD

**Issue by arashsa** [aichaos/rivescript-python#80]
In the JS version this seems to work, but not in the Python version.

```
! var test = Hi there

+ hi
- <bot test>

+ get lost
% <bot test>
- why?
```

**Comment by arashsa** [comment]
The same also applies for utf8 characters.

```
! var test = hæ there

+ hi
- <bot test>

+ get lost
% <bot test>
- why?

```

Anybody know how to fix this?

**Comment by kirsle** [comment]
This should be fixed using the current master branch of this repo. I'll do a deployment to PyPI later.

https://github.com/aichaos/rivescript-python/commit/5c5157455ff9a3f92f550d709435694940128f42

The root cause was that the `<bot test>` was returning a string with capital letters, so "Hi there" wasn't matching "hi there". I also fixed a similar issue with lowercasing `@Redirects` that I found on the Go version.
